name: Package Updates
on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: npm update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update packages
          title: Update packages
          body: |
            This is an automated pull request to update packages.
            Please review and merge if no issues are found.
            [Update](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})
          branch: updates/
          branch-suffix: timestamp
          delete-branch: true
          assignees: TraffordFewster
          author: <github-actions[bot]@users.noreply.github.com>


