name: Package Updates
on:
  schedule:
    - cron: '0 0 * * FRI'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update and store output file
        run: npm update &> output.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update packages
          title: Update packages
          body: |
            This is an automated pull request to update packages.
            Please review and merge if no issues are found.
            Output:
            ```
            $(cat output.txt)
            ```
          branch: updates/
          branch-suffix: timestamp
          delete-branch: true
          assignees: TraffordFewster


